name: todo_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  flare_flutter: ^3.0.2
  flutter_native_splash: ^2.4.1
  flutter_3d_controller: ^1.3.1
  flutter_local_notifications: ^17.2.2
  intl: ^0.19.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
 
  assets:
    - .env
    - assets/todo_pic.png

flutter_native_splash:
  color: "#42a5f5"
  image: assets/todo_pic.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: scaleAspectFit